[fmod]
group = Runtime
help = Settings for FMOD extension
title = FMOD

speaker_mode.type = string
speaker_mode.default = default
speaker_mode.options = default, raw, mono, stereo, quad, surround, 5.1, 7.1, max

num_buffers.type = integer

sample_rate.type = integer

num_raw_speakers.type = integer

run_while_iconified.type = bool

live_update.type = bool
live_update.default = 0

lib_path.type = string

buffer_length.type = integer
